apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitchat
spec:
  replicas: 1
  template:
    metadata:
      name: chitchat
      labels:
        app: chitchat
    spec:
      containers:
      - image: sys7/chitchat:latest
        name: nodejs

  selector:
    matchLabels:
     app: chitchat
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chitchat
  name: chitchat
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chitchat
  type: NodePort

